package net.sf.jxpilot.test;

/**
 * Class that contains the various keyboard numbers.
 * The keyboard is represented as a vector of bits.
 * Each bit set means that that key is toggled.
 * Might be better to use an enum here...
 * @author vlad
 */

public class Keys {
	public static final byte
	KEY_DUMMY=0,							/* 0 */
	KEY_LOCK_NEXT=1,
	KEY_LOCK_PREV=2,
	KEY_LOCK_CLOSE=3,
	KEY_CHANGE_HOME=4,
	KEY_SHIELD=5,							/* 5 */
	KEY_FIRE_SHOT=6,
	KEY_FIRE_MISSILE=7,
	KEY_FIRE_TORPEDO=8,
	KEY_TOGGLE_NUCLEAR=9,		/* Was KEY_FIRE_NUKE */
	KEY_FIRE_HEAT=10,						/* 10 */
	KEY_DROP_MINE=11,
	KEY_DETACH_MINE=12,
	KEY_TURN_LEFT=13,
	KEY_TURN_RIGHT=14,
	KEY_SELF_DESTRUCT=15,
	KEY_LOSE_ITEM=16,		/* Was KEY_ID_MODE up to 3.2.5 */
	KEY_PAUSE=17,
	KEY_TANK_DETACH=18,
	KEY_TANK_NEXT=19,
	KEY_TANK_PREV=20,						/* 20 */
	KEY_TOGGLE_VELOCITY=21,
	KEY_TOGGLE_CLUSTER=22,		/* Was KEY_TOGGLE_COMPASS */
	KEY_SWAP_SETTINGS=23,
	KEY_REFUEL=24,
	KEY_CONNECTOR=25,
	KEY_INCREASE_POWER=26,
	KEY_DECREASE_POWER=27,
	KEY_INCREASE_TURNSPEED=28,
	KEY_DECREASE_TURNSPEED=29,
	KEY_THRUST=30,							/* 30 */
	KEY_CLOAK=31,
	KEY_ECM=32,
	KEY_DROP_BALL=33,
	KEY_TRANSPORTER=34,
	KEY_TALK=35,
	KEY_FIRE_LASER=36,
	KEY_LOCK_NEXT_CLOSE=37,
	KEY_TOGGLE_COMPASS=38,
	KEY_TOGGLE_MINI=39,
	KEY_TOGGLE_SPREAD=40,						/* 40 */
	KEY_TOGGLE_POWER=41,
	KEY_TOGGLE_AUTOPILOT=42,
	KEY_TOGGLE_LASER=43,
	KEY_EMERGENCY_THRUST=44,
	KEY_TRACTOR_BEAM=45,
	KEY_PRESSOR_BEAM=46,
	KEY_CLEAR_MODIFIERS=47,
	KEY_LOAD_MODIFIERS_1=48,
	KEY_LOAD_MODIFIERS_2=49,
	KEY_LOAD_MODIFIERS_3=50,					/* 50 */
	KEY_LOAD_MODIFIERS_4=51,
	KEY_SELECT_ITEM=52,		/* Was KEY_TOGGLE_OWNED_ITEMS up to 3.2.5 */
	KEY_PHASING=53,		/* Was KEY_TOGGLE_MESSAGES up to 3.2.5 */
	KEY_REPAIR=54,
	KEY_TOGGLE_IMPLOSION=55,
	KEY_REPROGRAM=56,
	KEY_LOAD_LOCK_1=57,
	KEY_LOAD_LOCK_2=58,
	KEY_LOAD_LOCK_3=59,
	KEY_LOAD_LOCK_4=60,						/* 60 */
	KEY_EMERGENCY_SHIELD=61,
	KEY_HYPERJUMP=62,		/* Was KEY_POINTER_CONTROL up to 3.2.5 */
	KEY_DETONATE_MINES=63,
	KEY_DEFLECTOR=64,		/* since 3.8.0 */
	KEY_UNUSED_65=65,
	KEY_UNUSED_66=66,
	KEY_UNUSED_67=67,
	KEY_UNUSED_68=68,
	KEY_UNUSED_69=69,
	KEY_UNUSED_70=70,						/* 70 */
	KEY_UNUSED_71=71,
	NUM_KEYS=72;			/* The number of different keys*/

}
